CREATE TABLE MOVIE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    MOVIE_YEAR INT NOT NULL,
    WINNER BOOLEAN DEFAULT FALSE
);

CREATE TABLE STUDIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE MOVIE_STUDIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MOVIE_ID INT,
    STUDIO_ID INT,
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID) ON DELETE CASCADE,
    FOREIGN KEY (STUDIO_ID) REFERENCES STUDIO(ID) ON DELETE CASCADE
);

CREATE TABLE MOVIE_PRODUCER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MOVIE_ID INT,
    PRODUCER_ID INT,
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCER_ID) REFERENCES PRODUCER(ID) ON DELETE CASCADE
);
